name: tasks_repository
description: Dart package which manages the tasks interaction.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
#  flutter_secure_storage: ^8.0.0

